substitutions:
  # Name of the node. Don't use underscores!
  # https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  node_name: tion-o2
  # Name for the main entity and prefix for all others.
  friendly_name: $node_name
  # UART configuration.
  # Make sure to use YOUR pins!
  tx_pin: GPIO19
  rx_pin: GPIO20
  baud_rate: "115200"

  # WiFi settings.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: next # cant use substitutions here
    files:
      ## You can enable or disable some of the features listed below.
      ## The disabled feature starts with # symbol.
      ## The indentation before uncommented package is very important!

      ## Additional WiFi signal sensor.
      - packages/wifi_signal.yaml
      ## Additional Uptime sensor.
      - packages/uptime.yaml
      ## Additional Restart button.
      - packages/restart.yaml
      ## Unlock Tion 30°C heating.
      #- packages/tion_temperature30c.yaml
      ## Additional energy sensor.
      # - packages/tion_energy.yaml
      ## Antifrize protection. Automatically turns on the heater at a temperature of 0°C and below.
      - packages/tion_enable_antifrize.yaml
      ## Common configuration settings. Do not comment or move or remove!
      - packages/base.yaml
      ## Change to esp32.yaml/esp32_s2.yaml/esp32_c3.yaml to use with ESP32/ESP32-S2/ESP32-C3 chip.
      - packages/esp32_s3.yaml
      ## Internal ESP32 temperature sensor.
      # - packages/esp32_temperature.yaml
      ## Lilygo T-Dongle S3 internal LED and button support
      # - packages/lilygo.yaml
      ## Web server support.
      # - packages/web_server.yaml
      ## Additional debug information.
      # - packages/debug.yaml

# Uncomment to enable MQTT connecion.
# mqtt:
#   broker: !secret mqtt_borker
#   port: !secret mqtt_port
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   discovery: false # remove or set to true if you plan to use with Home Assistant

# Enable Home Assistant API connection. Please disable if you use MQTT
api:

# WiFi hotspot configuration.
# Comment next 3 lines to enable manual WiFi conviguration via access point.
wifi:
  ssid: $wifi_ssid
  password: $wifi_password

# Virtual port configuration
vport:
  - platform: tion_o2_uart
    id: tion_uart_vport
    uart_id: uart_tion
    ## Optional, Interval between sending commmands. Set to 0ms to send one command per loop.
    # command_interval: 20ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16

# Main climate component configuration.
# See detailed description and additional parameters at CONFIGURATION.md
tion:
  type: o2
  id: tion_api
  # Optional, use vport_id with mnultiple breezers.
  vport_id: tion_uart_vport
  # Optional, How often query device state. Default: 15s.
  update_interval: 15s
  # Optional, Timeout to combine update operations. Default: 200ms.
  batch_timeout: 200ms
  # Optional, Timeout to enable state problem sensor. Must be less than update_interval. Default: 3s.
  state_timeout: 3s
  # Optional, Updates sensor values on any state response or only if they have been changed. Default: false.
  force_update: false

  # Optional, Enable presets. Default: <empty> (no presets)
  # You can define any number of presets with any name.
  # In Home assistant climate entity presets with names home, away, boost, comfort,
  # eco, sleep and activity are automatically translated to your native language and assign icons.
  # Preset configuration:
  #  name_of_your_preset:
  #    fan_speed: 1            # remove or set to 0 to use current state
  #    temperature: 16         # remove or set to 0 to use current state
  #    heater: False           # remove to use current state
  #    power: True             #
  # Uncoment next 4 lines to enable example presets.
  # presets:
  #   home: { fan_speed: 2, target_temperature: 16, heater: False }
  #   away: { fan_speed: 1, target_temperature: 10, heater: False }
  #   sleep: { fan_speed: 1, target_temperature: 18 }

################################################################################
#
# Next sections set are only example configuration.
#
# In most cases it is enought, but if you prefer to customize please refer to
# CONFIGURATION.md for full set of available entities and options.
#
################################################################################

climate:
  - platform: tion
    name: None # use friendly_name
    # add HEAT_COOL mode to support turn_on without touching current heater mode.
    enable_heat_cool: True

sensor:
  # Temperatire of air before heater, °C (celsius).
  - platform: tion
    type: outdoor_temperature
    name: Outdoor Temperature
  # Current productivity, m³/h (cubic meters per hour).
  - platform: tion
    type: productivity
    name: Productivity
  # Filter time left counter.
  - platform: tion
    type: filter_time_left_days
    name: Filter Time Left
  # Boost time left sensor.
  - platform: tion
    type: boost_time_left
    name: Boost Time Left

switch:
  # Boost/Turbo switch.
  - platform: tion
    type: boost
    name: Boost
    # Optional, Heater state when boost enabled. If not set current state will be used.
    #heater: False
    # Optional, Target heater temperature state when boost enabled.
    #           If not set or set to 0 - current target temperture will be used.
    #temperature: 10

number:
  # Configure boost time.
  - platform: tion
    type: boost_time
    name: Boost Time
    initial_value: 20min
    restore_value: true

select:

binary_sensor:
  # Informs about state receiving problem from the breezer.
  - platform: tion
    type: state
    name: State Warning
  # Filter warning state.
  - platform: tion
    type: filter
    name: Filter Worn Out

text_sensor:
  # Tion firmware version.
  - platform: tion
    type: firmware_version
    name: Version
  # Reports Tion's errors (EC) and warnings (WS).
  - platform: tion
    type: errors
    name: Errors

button:

