substitutions:
  # Name of the node.
  # Don't use underscores.
  # https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  node_name: tion-3s
  # Name for the main entity and prefix for all others.
  friendly_name: $node_name
  # add suffix for node name to have one firmware for many devices.
  node_add_mac_suffix: "false"
  # Board
  board: esp01_1m
  # UART configuration.
  # Make sure to use YOUR pins!
  tx_pin: TX
  rx_pin: RX
  baud_rate: "115200"
  # UART proxy configuration (optional).
  # Make sure to use YOUR pins!
  proxy_tx_pin: GPIO15
  proxy_rx_pin: GPIO13
  proxy_baud_rate: "115200"

  # WiFi settings.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: next # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Enable additional Restart button. Comment next line to disable.
      - packages/restart.yaml
      ## Enable maximum target temperature to 30°C. Comment next line to disable.
      #- packages/tion_temperature30c.yaml
      ## Antifrize protection. Automatically turns on the heater at a temperature of 0°C and below.
      - packages/tion_enable_antifrize.yaml
      ## Common configuration settings. Do not comment or move or remove.
      - packages/base.yaml
      ## Change to packages/esp32.yaml if you want to use ESP32.
      - packages/esp8266.yaml
      ## Uncomment to enable BLE uart proxy support.
      #- packages/tion_3s_proxy.yaml
      ## Uncomment next line to enable web server support.
      # - packages/web_server.yaml
      ## Uncomment next line to enable additional debug information.
      # - packages/debug.yaml

# Uncomment to enable MQTT connecion.
# WARNINIG: If you leave next api section for logging purpose
#           and do not use Home Assistant, you need to uncomment
#           reboot_timeout parameter.
# mqtt:
#   broker: !secret mqtt_borker
#   port: !secret mqtt_port
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   discovery: false # remove or set to true if you plan to use with Home Assistant

# Enable Home Assistant API connection. Please do not remove to keep logs functioning.
api:
  # Uncomment next line if you do not use Home Assistant.
  #reboot_timeout: 0s

# WiFi hotspot configuration.
# Comment next 3 lines to enable manual WiFi conviguration via access point.
wifi:
  ssid: $wifi_ssid
  password: $wifi_password

# Virtual port configuration
vport:
  - platform: tion_3s_uart
    id: tion_uart_vport
    uart_id: uart_tion
    ## Optional, Interval between sending commmands. Set to 0ms to send one command per loop.
    # command_interval: 20ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16

# Main climate component configuration.
tion:
  type: 3s
  id: tion_api
  # Optional, use vport_id with mnultiple breezers.
  vport_id: tion_uart_vport
  # Optional, How often query device state. Default: 15s.
  update_interval: 15s
  # Optional, Timeout to combine update operations. Default: 200ms.
  batch_timeout: 200ms
  # Optional, Timeout to enable state problem sensor. Must be less than update_interval. Default: 3s.
  state_timeout: 3s
  # Optional, Updates sensor values on any state response or only if they have been changed. Default: true.
  force_update: false

  # Optional, Enable presets. Default: <empty> (no presets)
  # You can define any number of presets with any name.
  # In Home assistant climate entity presets with names home, away, boost, comfort,
  # eco, sleep and activity are automatically translated to your native language and assign icons.
  # Preset configuration:
  #  name_of_your_preset:
  #    fan_speed: 1            # remove or set to 0 to use current state
  #    temperature: 16         # remove or set to 0 to use current state
  #    heater: False           # remove to use current state
  #    power: True             #
  #    gate_position: outdoor  # remove to use current state, see below for available values
  # Available gate_position:
  #  * outdoor - set gate position to outdoor air intake (3S and 4S only)
  #  * indoor - set gate position to indoor air intake (3S and 4S only)
  #  * mixed - set gate position to mixed air intake (3S only)
  # Uncoment next 4 lines to enable example presets.
  # presets:
  #   home: { fan_speed: 2, target_temperature: 16, heater: False }
  #   away: { fan_speed: 1, target_temperature: 10, heater: False }
  #   sleep: { fan_speed: 1, target_temperature: 18 }

################################################################################
#
# Next sections set are only example configuration.
#
# In most cases it is enought, but if you prefer to customize please refer to
# CONFIGURATION.md for full set of available entities and options.
#
################################################################################

climate:
  - platform: tion
    name: None # use friendly_name
    # add HEAT_COOL mode to support turn_on without touching current heater mode.
    enable_heat_cool: True

sensor:
  # Temperatire of air before heater, °C (celsius).
  - platform: tion
    type: outdoor_temperature
    name: Outdoor Temperature
  # Current productivity, m³/h (cubic meters per hour).
  - platform: tion
    type: productivity
    name: Productivity
  # Filter time left counter.
  - platform: tion
    type: filter_time_left
    name: Filter Time Left
  # Boost time left sensor.
  - platform: tion
    type: boost_time_left
    name: Boost Time Left

switch:
  # Buzzer control switch.
  - platform: tion
    type: sound
    name: Buzzer
  # Boost/Turbo switch.
  - platform: tion
    type: boost
    name: Boost
    # Optional, Heater state when boost enabled. If not set current state will be used.
    #heater: False
    # Optional, Target heater temperature state when boost enabled.
    #           If not set or set to 0 - current target temperture will be used.
    #temperature: 10

number:
  # Configure boost time.
  - platform: tion
    type: boost_time
    name: Boost Time
    initial_value: 20min
    restore_value: true

select:
    # Optional, Air Intake control.
  - platform: tion
    type: air_intake
    name: Air Intake

binary_sensor:
  # Informs about state receiving problem from the breezer.
  - platform: tion
    type: state
    name: State Warnout
  # Filter warning state.
  - platform: tion
    type: filter
    name: Filter Warnout

text_sensor:
  # Tion firmware version.
  - platform: tion
    type: firmware_version
    name: Version
  # Reports Tion's errors (EC) and warnings (WS).
  - platform: tion
    type: errors
    name: Errors

button:
  # Reset filter button.
  - platform: tion
    type: reset_filter
    name: Reset Filter
    # Reset filter confirmation. When off then reset_filter will not work.
    confirm:
      name: Reset Filter Confirm

