substitutions:
  name: $node_name
  board: esp32dev
  # framework settings: esp-idf or arduino
  framework_type: arduino
  node_add_mac_suffix: "true"
  tion_version: 2022.10.0
  tion_source: github://dentra/esphome-tion@$tion_version

esphome:
  name: $node_name
  name_add_mac_suffix: $node_add_mac_suffix
  project:
    name: "dentra.tion"
    version: "$tion_version ($framework_type)"

esp32:
  board: $board
  framework:
    type: $framework_type

preferences:
  flash_write_interval: 10min

wifi:
  ap:
    ssid: "$name Fallback Hotspot"
# captive_portal:

api:

ota:
  on_begin:
    then:
      - lambda: id(tion_ble_client).set_enabled(false);

logger:

esp32_ble_tracker:

external_components:
  - source: github://dentra/esphome-components
    components: [crash_info, etl]
  - source: $tion_source
