substitutions:
  board: esp32dev

esp32:
  board: $board
  framework:
    type: $framework_type

wifi:
  power_save_mode: none

esp32_ble_tracker:

ble_client:
  mac_address: $tion_mac_address
  id: tion_ble_client

ota:
  on_begin:
    then:
      lambda: id(tion_ble_client).set_enabled(false);
