substitutions:
  board: esp32-c6-devkitc-1

packages:
  tion.esp32_uart: !include esp32_uart.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: $board
  variant: ESP32C6

