substitutions:
  board: esp32dev

esp32:
  board: $board
  framework:
    type: esp-idf
    # eshhome 2023.12.x, version: 4.4.5 platform_version: 5.4.0
    # esphome 2024.5.x, version: 4.4.7, platform_version: 5.4.0
    # esp-idf 5.2.1,  version: 5.2.1, platform_version: 6.7.0
    version: 4.4.7 # pin esp-idf

wifi:
  power_save_mode: light

esp32_ble_tracker:
  id: tion_esp32_ble_tracker

ble_client:
  - mac_address: $tion_mac_address
    id: tion_ble_client

ota:
  - id: !extend esphome_ota
    platform: esphome
    on_begin:
      then:
        lambda: |-
          id(tion_ble_client).set_enabled(false);
