substitutions:
  board: esp32dev

packages:
  # pin the esp-idf framework to 4.4.7
  pin_esp_idf: !include esp-idf-4.4.7.yaml

esp32:
  board: $board

wifi:
  power_save_mode: light

esp32_ble_tracker:
  id: tion_esp32_ble_tracker

ble_client:
  - mac_address: $tion_mac_address
    id: tion_ble_client

ota:
  - id: !extend esphome_ota
    platform: esphome
    on_begin:
      then:
        lambda: |-
          id(tion_ble_client).set_enabled(false);
