substitutions:
  board: dfrobot_beetle_esp32c3
  tx_pin: GPIO20
  rx_pin: GPIO19

packages:
  tion.esp32_uart: !include esp32_uart.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

# esp32_usb_dis:
