substitutions:
  board: esp32-c3-devkitm-1

packages:
  tion.esp32_ble: !include esp32_ble.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32_ble:
  enable_on_boot: false

wifi:
  on_connect:
    - ble.enable
