substitutions:
  board: esp32-s3-devkitc-1

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: $board
  framework:
    type: esp-idf

wifi:
  power_save_mode: light

esp32_ble_tracker:

ble_client:
  mac_address: $tion_mac_address
  id: tion_ble_client

ota:
  on_begin:
    then:
      lambda: id(tion_ble_client).set_enabled(false);
