substitutions:
  board: esp32dev
  tx_pin: TX
  rx_pin: RX
  baud_rate: "9600"

esp32:
  board: $board
  framework:
    type: esp-idf

logger:
  # Make sure logging is not using the serial port
  baud_rate: 0
  logs:
    esp-idf: INFO

uart:
  - id: tion_uart
    tx_pin: $tx_pin
    rx_pin: $rx_pin
    baud_rate: $baud_rate
