substitutions:
  use_seeed_c6_external_antenna: "false"

declaration:
  - lambda: |-
      bool use_seeed_c6_external_antenna = $use_seeed_c6_external_antenna;

settings:
  variables:
    seeed_external_ant:
      name: Use external antenna
      help: Enable usage of an external antenna
      type: bool
      getter: |-
        return use_seeed_c6_external_antenna;
      setter: |-
        use_seeed_c6_external_antenna = x;

esphome:
  on_boot:
    - priority: 800
      then:
        if:
          condition:
            - lambda: |-
                return use_seeed_c6_external_antenna;
          then:
            - lambda: |-
                gpio_num_t gpio_enable_ext_antenna = ::GPIO_NUM_3;
                gpio_reset_pin    (gpio_enable_ext_antenna);
                gpio_set_direction(gpio_enable_ext_antenna, GPIO_MODE_OUTPUT);
                gpio_set_level    (gpio_enable_ext_antenna, 0); // turn on this function
            - delay: 100ms
            - lambda: |-
                gpio_num_t gpio_select_ext_antenna = ::GPIO_NUM_14;
                gpio_reset_pin    (gpio_select_ext_antenna);
                gpio_set_direction(gpio_select_ext_antenna, GPIO_MODE_OUTPUT);
                gpio_set_level    (gpio_select_ext_antenna, 1); // use external antenna
            - logger.log:
                level: info
                format: External antenna was activated
