packages:
  mqtt: !include mqtt.yaml

esphome:
  platformio_options:
    build_flags:
      # Включаем поддержку работы со SprutHub
      - -DTION_SPRUTHUB_SUPPORT

mqtt:
  discovery: false
  publish_nan_as_none: false
