esphome:
  platformio_options:
    build_flags:
      # Включаем поддержку работы с расписанием
      - -DTION_ENABLE_SCHEDULER

button:
  # Позволяет получить в логе информацию о всех существующих таймерах
  - platform: template
    id: tion_dump_timers
    name: Dump Timers
    icon: mdi:timer-check-outline
    on_press:
      - lambda: id(tion_api).dump_timers();
    entity_category: diagnostic
  # Позволяет сбросить все существующие таймеры
  - platform: template
    id: tion_reset_timers
    name: Reset Timers
    icon: mdi:timer-remove-outline
    on_press:
      - lambda: id(tion_api).reset_timers();
    entity_category: diagnostic
