name: ci

on:
  push:
    branches: [next]
  pull_request:
  schedule:
    # Once per week on wednesday
    - cron: 0 12 * * 3

env:
  FORCE_COLOR: 1
  ESPHOME_VERSION: "2024.12.4"
  PYTHON_VERSION: "3.12"
  ESPHOME_DATA_DIR: ".esphome"

jobs:
  build:
    if: startsWith(github.server_url, 'https://github.com')
    runs-on: ubuntu-latest
    outputs:
      firmware-path: ${{ steps.esphome.outputs.firmware-path }}
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        component:
          - tion-o2-uart
          - tion-3s-ble
          - tion-3s-uart
          - tion-4s-ble
          - tion-4s-uart
          - tion-lt-ble
          - tion-lt-uart
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Generate fake secrets.yaml
        run: |
          echo -e "wifi_ssid: ssid\nwifi_password: password" > tests/cfg/secrets.yaml
      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/clang-tidy.json"
          echo "::add-matcher::.github/workflows/matchers/gcc.json"
      - name: Build project
        uses: dentra/esphome-action@main
        id: esphome
        with:
          version: ${{ env.ESPHOME_VERSION }}
          config: tests/cfg/${{ matrix.component }}.yaml
          substitutions: |
            {
              "project_version": "test",
              "project_name": "${{ matrix.component }}",
              "project_source": "../../components",
              "project_branch": "${{ github.ref_name }}"
            }
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Show firmware artifacts
        run: |
          env
          ls -la .
          ls -la .esphome
          ls -la .esphome/builds
          ls -l ${{ steps.esphome.outputs.firmware-path }}/firmware.*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}-test-${{ github.run_id }}.zip
          path: |
            ${{ steps.esphome.outputs.firmware-path }}/firmware.*
            !${{ steps.esphome.outputs.firmware-path }}/firmware.bin
          retention-days: 3
          if-no-files-found: error
